import 'package:flutter/cupertino.dart';

import '../../../../../../generated/l10n.dart';

List<String> getPrivacySections(BuildContext context) {
  return [
    S.of(context).section1,
    S.of(context).section2,
    S.of(context).section3,
    S.of(context).section4,
    S.of(context).section5,
    S.of(context).section6,
    S.of(context).section7,
    S.of(context).section8,
    S.of(context).section9,
    S.of(context).section10,
    S.of(context).section11,
    S.of(context).section12,
    S.of(context).section13,
    S.of(context).section14,
    S.of(context).section15,
    S.of(context).section16,
    S.of(context).section17,
    S.of(context).section18,
    S.of(context).section19,
    S.of(context).section20,
    S.of(context).section21,
    S.of(context).section22,
    S.of(context).section23,
    S.of(context).section24,
    S.of(context).section25,
    S.of(context).section26,
    S.of(context).section27,
    S.of(context).section28,
    S.of(context).section29,
    S.of(context).section30,
    S.of(context).section31,
    S.of(context).section32,
    S.of(context).section33,
    S.of(context).section34,
    S.of(context).section35,
    S.of(context).section36,
    S.of(context).section37,
    S.of(context).section38,
    S.of(context).section39,
    S.of(context).section40,
    S.of(context).section41,
    S.of(context).section42,
    S.of(context).section43,
    S.of(context).section44,
    S.of(context).section45,
    S.of(context).section46,
  ];
}
