final Map<String, List<String>> governoratesWithCities = {
  'Cairo': [
    'Maadi',
    'Mokattam',
    'Nasr City',
    'Zamalek',
    'Dokki',
    'Heliopolis',
    'Shubra',
    'New Cairo',
    'El Marg',
  ],
  'Giza': [
    'Dokki',
    'Mohandessin',
    'Haram',
    '6th October',
    'Sheikh Zayed',
    'Faisal',
    'Bulaq Dakrour',
    'Imbaba',
  ],
  'Alexandria': [
    'Smouha',
    'Sidi Gaber',
    'Asafra',
    'Mandara',
    'Montaza',
    'Gleem',
    'Stanley',
    'Miami',
    'San Stefano',
  ],
  'Minya': [
    'New Minya',
    'Mallawi',
    'Deir Mawas',
    'Maghagha',
    'Abu Qurqas',
    'Samalout',
    'Beni Mazar',
  ],
  'Assiut': [
    'New Assiut',
    'Dayrout',
    'Sadfa',
    'El Badari',
    'Abnoub',
    'El Quseyya',
    'Manfalut',
  ],
  'Sohag': ['Akhmim', 'Gerga', 'El Maragha', 'Tahta', 'Sohag City', 'Tama'],
  'Qena': ['Qena City', 'Nag Hammadi', 'Qift', 'Farshout', 'Deshna'],
  'Luxor': ['Luxor City', 'Esna', 'Armant', 'El-Toud', 'New Tiba'],
  'Aswan': ['Aswan City', 'Kom Ombo', 'Edfu', 'Daraw', 'New Aswan'],
  'Red Sea': ['Hurghada', 'Safaga', 'Quseir', 'Marsa Alam', 'Shalateen'],
  'South Sinai': [
    'Sharm El-Sheikh',
    'Dahab',
    'Nuweiba',
    'Saint Catherine',
    'Taba'
  ],
  'North Sinai': ['Arish', 'Bir al-Abd', 'Sheikh Zuweid', 'Rafah'],
  'Ismailia': ['Ismailia City', 'Fayed', 'Qantara West', 'Tell El Kebir'],
  'Port Said': ['Port Said City', 'Port Fouad'],
  'Suez': ['Suez City', 'Ain Sokhna', 'Ataqa'],
  'Beheira': ['Damanhour', 'Kafr El Dawwar', 'Edku', 'Rashid', 'Abu Hummus'],
  'Dakahlia': ['Mansoura', 'Talkha', 'Mit Ghamr', 'Sherbin', 'Belqas'],
  'Sharqia': [
    'Zagazig',
    '10th of Ramadan',
    'Bilbeis',
    'Minya El Qamh',
    'Fakous'
  ],
  'Gharbia': [
    'Tanta',
    'El Mahalla El Kubra',
    'Kafr El Zayat',
    'Zifta',
    'Samanoud'
  ],
  'Monufia': ['Shibin El Kom', 'Sadat City', 'Ashmoun', 'Quesna', 'Menouf'],
  'Fayoum': [
    'Fayoum City',
    'Senoures',
    'Etsa',
    'Tamiya',
    'Youssef El Seddik'
  ],
  'Beni Suef': ['Beni Suef City', 'Nasser', 'Biba', 'El Wasta', 'Ihnasya'],
  'Kafr El Sheikh': [
    'Kafr El Sheikh City',
    'Desouk',
    'Baltim',
    'Motobas',
    'Fuwwah'
  ],
  'Damietta': [
    'Damietta City',
    'New Damietta',
    'Ras El Bar',
    'Ezbet El Borg',
    'Kafr Saad'
  ],
  'New Valley': ['Kharga', 'Dakhla', 'Baris', 'Farafra'],
  'Matrouh': [
    'Marsa Matrouh',
    'Siwa',
    'El Alamein',
    'Sidi Barrani',
    'Al Negila'
  ],
};
