import 'RealStateObjects.dart';

final List<RealStateObjects> defaultApartments = [
  RealStateObjects(
    name: 'Luxury Apartment',
    type: 'Apartment',
    images: [
      'Assets/30d6e5a3-9774-4ba7-a03f-3c2f32b99d24.jpeg',
      'Assets/2f16b3f2-2b9b-4231-8768-5e09cb827110.jpeg',
    ],
    location: 'Cairo',
    address: 'Street, 15',
    baths: 2,
    beds: 4,
    size: 180,
    price: '4,200,000',
    description: 'Experience luxury living with stunning city views and modern amenities.',
    finishingType: 'Unfinished',
    listingDate: '12/4/2025',
    ownerNumber: '01017900067',
    deliveryType: '2026',
    PaymentDetails: 'Cash',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Cozy Villa',
    type: 'Villa',
    images: [
      'Assets/movie-night-by-pool-whole-family.jpg',
      'Assets/house-isolated-field.jpg',
    ],
    location: 'Alexandria',
    address: 'Coastal Road',
    baths: 3,
    beds: 5,
    size: 250,
    price: '8,000,000',
    description: 'A beautiful villa with a private pool and garden.',
    finishingType: 'Fully Finished',
    listingDate: '1/3/2025',
    ownerNumber: '01017900067',
    deliveryType: '2027',
    PaymentDetails: 'Installments',
    isForRent: true,
  ),
  RealStateObjects(
    name: 'Modern Office',
    type: 'Office',
    images: [
      'Assets/modern-office-space-with-futuristic-decor-furniture.jpg',
      'Assets/3d-rendering-luxury-business-meeting-working-room-executive-office.jpg',    ],
    location: 'Giza',
    address: 'Business Park',
    baths: 1,
    beds: 0,
    size: 120,
    price: '2,500,000',
    description: 'A modern office space with great facilities.',
    finishingType: 'Fully Finished',
    listingDate: '10/5/2025',
    ownerNumber: '01017900067',
    deliveryType: '2026',
    PaymentDetails: 'Installment over 10 Years',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Studio Apartment',
    type: 'Apartment',
    images: [
      'Assets/shot-panoramic-composition-bedroom.jpg',
      'Assets/2f16b3f2-2b9b-4231-8768-5e09cb827110.jpeg',
    ],
    location: 'Cairo',
    address: 'Downtown',
    baths: 1,
    beds: 1,
    size: 80,
    price: '1,800,000',
    description: 'A cozy studio apartment in the heart of the city.',
    finishingType: 'Semi Finished',
    listingDate: '15/6/2025',
    ownerNumber: '01017900067',
    deliveryType: '2026',
    PaymentDetails: 'Installment over 2 Years',
    isForRent: true,
  ),
  RealStateObjects(
    name: 'Luxury Villa',
    type: 'Villa',
    images: [
      'Assets/house-isolated-field.jpg',
      'Assets/movie-night-by-pool-whole-family.jpg',
    ],
    location: 'Sharm El Sheikh',
    address: 'Sea View Road',
    baths: 4,
    beds: 6,
    size: 300,
    price: '12,000,000',
    description: 'A luxurious villa with a stunning sea view.',
    finishingType: 'Fully Finished',
    listingDate: '20/7/2025',
    ownerNumber: '01017900067',
    deliveryType: '2027',
    PaymentDetails: 'Cash',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Commercial Office',
    type: 'Office',
    images: [
      'Assets/room-used-official-event.jpg',
      'Assets/3d-rendering-luxury-business-meeting-working-room-executive-office.jpg',
    ],
    location: 'New Cairo',
    address: 'Business District',
    baths: 2,
    beds: 0,
    size: 150,
    price: '3,000,000',
    description: 'A commercial office space in a prime location.',
    finishingType: 'Fully Finished',
    listingDate: '25/8/2025',
    ownerNumber: '01017900067',
    deliveryType: '2026',
    PaymentDetails: 'Cash',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Luxury Apartment in New Cairo',
    type: 'Apartment',
    images: [
      'Assets/30d6e5a3-9774-4ba7-a03f-3c2f32b99d24.jpeg',
      'Assets/2f16b3f2-2b9b-4231-8768-5e09cb827110.jpeg',
    ],
    location: 'New Cairo',
    address: '90th Street, Tower 12',
    baths: 2,
    beds: 3,
    size: 150,
    price: '2,500,000',
    description: 'A luxury apartment in a prime location with a stunning city view.',
    finishingType: 'Fully Finished',
    listingDate: '10/10/2023',
    ownerNumber: '01012345678',
    deliveryType: '2040',
    PaymentDetails: 'Installment over 10 Years',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Apartment for Rent in Maadi',
    type: 'Apartment',
    images: [
      'Assets/30d6e5a3-9774-4ba7-a03f-3c2f32b99d24.jpeg',
      'Assets/2f16b3f2-2b9b-4231-8768-5e09cb827110.jpeg',
    ],
    location: 'Maadi',
    address: '9th Street, Building 25',
    baths: 1,
    beds: 2,
    size: 100,
    price: '5,000',
    description: 'A modern apartment for rent in a quiet area close to all amenities.',
    finishingType: 'Semi Finished',
    listingDate: '09/15/2023',
    ownerNumber: '01087654321',
    deliveryType: '2025',
    PaymentDetails: 'Installment over 10 Years',
    isForRent: true,
  ),

  // Villas
  RealStateObjects(
    name: 'Villa for Sale in Sheikh Zayed',
    type: 'Villa',
    images: [
      'Assets/movie-night-by-pool-whole-family.jpg',
      'Assets/house-isolated-field.jpg',
    ],
    location: 'Sheikh Zayed',
    address: 'Al Yasmeen Compound, Villa 12',
    baths: 4,
    beds: 5,
    size: 300,
    price: '8,000,000',
    description: 'A luxury villa with a private garden and swimming pool in an upscale compound.',
    finishingType: 'Semi Finished',
    listingDate: '08/20/2023',
    ownerNumber: '01011223344',
    deliveryType: '2028',
    PaymentDetails: 'Installment over 2 Years',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Villa for Rent in North Coast',
    type: 'Villa',
    images: [
      'Assets/house-isolated-field.jpg',
      'Assets/movie-night-by-pool-whole-family.jpg',
    ],
    location: 'North Coast',
    address: 'Marina Compound, Villa 7',
    baths: 3,
    beds: 4,
    size: 250,
    price: '20,000',
    description: 'A stylish seasonal rental villa with a sea view.',
    finishingType: 'Semi Finished',
    listingDate: '07/05/2023',
    ownerNumber: '01055667788',
    deliveryType: '2030',
    PaymentDetails: 'Installment over 6 Years',
    isForRent: true,
  ),
  RealStateObjects(
    name: 'Office for Sale in Fifth Settlement',
    type: 'Office',
    images: [
      'Assets/photorealistic-environment-lawyer.jpg',
      'Assets/3d-rendering-luxury-business-meeting-working-room-executive-office.jpg',
    ],
    location: 'Fifth Settlement',
    address: 'Business Tower, 10th Floor',
    baths: 2,
    beds: 0,
    size: 120,
    price: '3,500,000',
    description: 'A luxurious office in a strategic location near all services.',
    finishingType: 'Semi Finished',
    listingDate: '06/12/2023',
    ownerNumber: '01099887766',
    deliveryType: '2025',
    PaymentDetails: 'Cash',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Office for Rent in Nasr City',
    type: 'Office',
    images: [
      'Assets/photorealistic-environment-lawyer.jpg',
      'Assets/3d-rendering-luxury-business-meeting-working-room-executive-office.jpg',
    ],
    location: 'Nasr City',
    address: 'Mostafa El-Nahas Street, Building 15',
    baths: 1,
    beds: 0,
    size: 80,
    price: '8,000',
    description: 'A modern office for rent in a prime location near public transportation.',
    finishingType: 'Semi Finished',
    listingDate: '05/25/2023',
    ownerNumber: '01033445566',
    deliveryType: '2025',
    PaymentDetails: 'Installment over 10 Years',
    isForRent: true,
  ),

  // Additional examples
  RealStateObjects(
    name: 'Duplex Apartment in Al Rehab',
    type: 'Apartment',
    images: [
      'Assets/30d6e5a3-9774-4ba7-a03f-3c2f32b99d24.jpeg',
      'Assets/2f16b3f2-2b9b-4231-8768-5e09cb827110.jpeg',
    ],
    location: 'Al Rehab',
    address: 'Al Rehab Compound, Building 8',
    baths: 3,
    beds: 4,
    size: 200,
    price: '4,000,000',
    description: 'A luxurious duplex apartment with a garden view.',
    finishingType: 'Semi Finished',
    listingDate: '04/30/2023',
    ownerNumber: '01022334455',
    deliveryType: '2023',
    PaymentDetails: 'Installment over 5 Years',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Luxury Villa in Hurghada',
    type: 'Villa',
    images: [
      'Assets/movie-night-by-pool-whole-family.jpg',
      'Assets/house-isolated-field.jpg',
    ],
    location: 'Hurghada',
    address: 'Red Sea Compound, Villa 3',
    baths: 5,
    beds: 6,
    size: 400,
    price: '12,000,000',
    description: 'A luxury villa with a direct sea view and a private pool.',
    finishingType: 'Semi Finished',
    listingDate: '03/15/2023',
    ownerNumber: '01066778899',
    deliveryType: '2025',
    PaymentDetails: 'Installment over 2 Years',
    isForRent: false,
  ),
  RealStateObjects(
    name: 'Office in Cairo Tower',
    type: 'Office',
    images: [
      'Assets/3d-rendering-luxury-business-meeting-working-room-executive-office.jpg',
      'Assets/photorealistic-environment-lawyer.jpg',
    ],
    location: 'Downtown',
    address: 'Cairo Tower, 20th Floor',
    baths: 2,
    beds: 0,
    size: 150,
    price: '5,000,000',
    description: 'A luxurious office in Cairo Tower with a panoramic city view.',
    finishingType: 'Semi Finished',
    listingDate: '02/10/2023',
    ownerNumber: '01044556677',
    deliveryType: '2025',
    PaymentDetails: 'Cash',
    isForRent: false,
  ),
];